backend:
  name: git-gateway
  branch: master

site_url: https://masksforhunger.com
display_url: https://masksforhunger.com
logo_url: https://masksforhunger.com/logo.svg

media_folder: static/assets
public_folder: /assets
collections:
  - name: catalog
    label: Mask
    folder: catalog
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: quantity, label: Quantity Remaining, widget: number }
      - name: "color"
        label: "Color"
        widget: "select"
        options: ["gray", "blue", "brown", "beige", "black", "red", "orange", "green"]
